import { Message } from 'discord.js';

export async function cmdHelp(message: Message): Promise<void> {
  const lines = [
    'PREFIX: +                          (all commands — admins only)',
    '',
    'MODERATION',
    '----------',
    '+ban @user [reason]          Ban a member from the server',
    '+kick @user [reason]         Kick a member from the server',
    '+mute @user <dur> [reason]   Timeout a member (e.g. 10m, 2h, 1d)',
    '+unmute @user                Remove a member\'s timeout',
    '+warn @user [reason]         Issue a warning to a member',
    '+warnings @user              View all warnings for a member',
    '+clearwarnings @user         Clear all warnings for a member',
    '',
    'CHANNEL',
    '-------',
    '+purge <1-100>               Delete messages in the current channel',
    '+slowmode <seconds>          Set slowmode (0 to disable)',
    '+lock                        Prevent members from sending messages',
    '+unlock                      Restore member messaging in channel',
    '',
    'ROLES',
    '-----',
    '+role @user @role            Add/remove a role from a member',
    '',
    'INFO',
    '----',
    '+userinfo [@user]            Show account and membership details',
    '+serverinfo                  Show server details',
    '+lookup <year>               List members whose accounts were made in that year',
    '+lookupnitro                 List members with Nitro indicators',
    '',
    'MESSAGING',
    '---------',
    '+dm @user <message>          DM a specific member',
    '+dm all <message>            DM every member in the server',
    '',
    'VERIFICATION',
    '------------',
    '+verifysetup <url>           Post a verification panel with a GIF/image and Access button',
    '                             Members click it, get a one-time link, complete 3 steps online,',
    '                             and are automatically given the "verif" role.',
    '',
    'AUTO BEHAVIOR',
    '-------------',
    'Ghost ping   New members are ghost-pinged in #verify on join',
  ];

  await message.reply(`\`\`\`\n${lines.join('\n')}\n\`\`\``);
}
